name: Dump Opendot API
description: Dump Opendot API for GDExtension

inputs:
  bin:
    description: The path to the Opendot executable
    required: true

runs:
  using: composite
  steps:
    # Dump GDExtension interface and API
    - name: Dump GDExtension interface and API for opendot-cpp build
      shell: sh
      run: |
        ${{ inputs.bin }} --headless --dump-gdextension-interface --dump-extension-api
        mkdir opendot-api
        cp -f gdextension_interface.h opendot-api/
        cp -f extension_api.json opendot-api/

    - name: Upload API dump
      uses: ./.github/actions/upload-artifact
      with:
        name: opendot-api-dump
        path: ./opendot-api/*
